Fix Nexus URLs
ibissource/frank-runner pull request #20
Opened 2021-03-17 14:48 UTC by ricardovh

2021-03-17 15:31 UTC, nielsm5 requested changes

2021-03-17 15:31 UTC, nielsm5 commented on build.xml
> +		<get src="https://nexus.ibissource.org/repository/public/org/ibissource/ibis-adapterframework-core/maven-metadata.xml" dest="download/metadata/maven-metadata-tmp.xml" maxtime="${get.metadata.maxtim
je moet hier wel webapp blijven gebruiken

2021-03-17 15:39 UTC, ricardovh commented on build.xml
> +		<get src="https://nexus.ibissource.org/repository/public/org/ibissource/ibis-adapterframework-core/maven-metadata.xml" dest="download/metadata/maven-metadata-tmp.xml" maxtime="${get.metadata.maxtim
Oeps, gefixt

2021-03-17 16:10 UTC, nielsm5 requested changes
Kan jij ook https://nexus.ibissource.org aanpassen naar https://nexus.frankframework.org

2021-03-18 09:14 UTC, jacodg approved these changes

2021-03-18 09:15 UTC, merged